INSERT INTO country (country_id,country_name) VALUES (1,'Afganistan'); 
INSERT INTO country (country_id,country_name) VALUES (2,'Akrotiri'); 
INSERT INTO country (country_id,country_name) VALUES (3,'Albania'); 
INSERT INTO country (country_id,country_name) VALUES (4,'Alemania'); 
INSERT INTO country (country_id,country_name) VALUES (5,'Andorra'); 
INSERT INTO country (country_id,country_name) VALUES (6,'Angola'); 
INSERT INTO country (country_id,country_name) VALUES (7,'Anguila'); 
INSERT INTO country (country_id,country_name) VALUES (8,'Antartida'); 
INSERT INTO country (country_id,country_name) VALUES (9,'Antigua y Barbuda'); 
INSERT INTO country (country_id,country_name) VALUES (10,'Antillas Neerlandesas'); 
INSERT INTO country (country_id,country_name) VALUES (11,'Arabia Saudi'); 
INSERT INTO country (country_id,country_name) VALUES (12,'Arctic Ocean'); 
INSERT INTO country (country_id,country_name) VALUES (13,'Argelia'); 
INSERT INTO country (country_id,country_name) VALUES (14,'Argentina'); 
INSERT INTO country (country_id,country_name) VALUES (15,'Armenia'); 
INSERT INTO country (country_id,country_name) VALUES (16,'Aruba'); 
INSERT INTO country (country_id,country_name) VALUES (17,'Ashmore andCartier Islands'); 
INSERT INTO country (country_id,country_name) VALUES (18,'Atlantic Ocean'); 
INSERT INTO country (country_id,country_name) VALUES (19,'Australia'); 
INSERT INTO country (country_id,country_name) VALUES (20,'Austria'); 
INSERT INTO country (country_id,country_name) VALUES (21,'Azerbaiyan'); 
INSERT INTO country (country_id,country_name) VALUES (22,'Bahamas'); 
INSERT INTO country (country_id,country_name) VALUES (23,'Bahrain'); 
INSERT INTO country (country_id,country_name) VALUES (24,'Bangladesh'); 
INSERT INTO country (country_id,country_name) VALUES (25,'Barbados'); 
INSERT INTO country (country_id,country_name) VALUES (26,'Belgica'); 
INSERT INTO country (country_id,country_name) VALUES (27,'Belice'); 
INSERT INTO country (country_id,country_name) VALUES (28,'Benin'); 
INSERT INTO country (country_id,country_name) VALUES (29,'Bermudas'); 
INSERT INTO country (country_id,country_name) VALUES (30,'Bielorrusia'); 
INSERT INTO country (country_id,country_name) VALUES (31,'Birmania Myanmar'); 
INSERT INTO country (country_id,country_name) VALUES (32,'Bolivia'); 
INSERT INTO country (country_id,country_name) VALUES (33,'Bosnia y Hercegovina'); 
INSERT INTO country (country_id,country_name) VALUES (34,'Botsuana'); 
INSERT INTO country (country_id,country_name) VALUES (35,'Brasil'); 
INSERT INTO country (country_id,country_name) VALUES (36,'Brunei'); 
INSERT INTO country (country_id,country_name) VALUES (37,'Bulgaria'); 
INSERT INTO country (country_id,country_name) VALUES (38,'Burkina Faso'); 
INSERT INTO country (country_id,country_name) VALUES (39,'Burundi'); 
INSERT INTO country (country_id,country_name) VALUES (40,'Butan'); 
INSERT INTO country (country_id,country_name) VALUES (41,'Cabo Verde'); 
INSERT INTO country (country_id,country_name) VALUES (42,'Camboya'); 
INSERT INTO country (country_id,country_name) VALUES (43,'Camerun'); 
INSERT INTO country (country_id,country_name) VALUES (44,'Canada'); 
INSERT INTO country (country_id,country_name) VALUES (45,'Chad'); 
INSERT INTO country (country_id,country_name) VALUES (46,'Chile'); 
INSERT INTO country (country_id,country_name) VALUES (47,'China'); 
INSERT INTO country (country_id,country_name) VALUES (48,'Chipre'); 
INSERT INTO country (country_id,country_name) VALUES (49,'Clipperton Island'); 
INSERT INTO country (country_id,country_name) VALUES (50,'Colombia'); 
INSERT INTO country (country_id,country_name) VALUES (51,'Comoras'); 
INSERT INTO country (country_id,country_name) VALUES (52,'Congo'); 
INSERT INTO country (country_id,country_name) VALUES (53,'Coral Sea Islands'); 
INSERT INTO country (country_id,country_name) VALUES (54,'Corea del Norte'); 
INSERT INTO country (country_id,country_name) VALUES (55,'Corea del Sur'); 
INSERT INTO country (country_id,country_name) VALUES (56,'Costa de Marfil'); 
INSERT INTO country (country_id,country_name) VALUES (57,'Costa Rica'); 
INSERT INTO country (country_id,country_name) VALUES (58,'Croacia'); 
INSERT INTO country (country_id,country_name) VALUES (59,'Cuba'); 
INSERT INTO country (country_id,country_name) VALUES (60,'Dhekelia'); 
INSERT INTO country (country_id,country_name) VALUES (61,'Dinamarca'); 
INSERT INTO country (country_id,country_name) VALUES (62,'Dominica'); 
INSERT INTO country (country_id,country_name) VALUES (63,'Ecuador'); 
INSERT INTO country (country_id,country_name) VALUES (64,'Egipto'); 
INSERT INTO country (country_id,country_name) VALUES (65,'El Salvador'); 
INSERT INTO country (country_id,country_name) VALUES (66,'El Vaticano'); 
INSERT INTO country (country_id,country_name) VALUES (67,'Emiratos arabes Unidos'); 
INSERT INTO country (country_id,country_name) VALUES (68,'Eritrea'); 
INSERT INTO country (country_id,country_name) VALUES (69,'Eslovaquia'); 
INSERT INTO country (country_id,country_name) VALUES (70,'Eslovenia'); 
INSERT INTO country (country_id,country_name) VALUES (71,'Espana'); 
INSERT INTO country (country_id,country_name) VALUES (72,'Estados Unidos'); 
INSERT INTO country (country_id,country_name) VALUES (73,'Estonia'); 
INSERT INTO country (country_id,country_name) VALUES (74,'Etiopia'); 
INSERT INTO country (country_id,country_name) VALUES (75,'Filipinas'); 
INSERT INTO country (country_id,country_name) VALUES (76,'Finlandia'); 
INSERT INTO country (country_id,country_name) VALUES (77,'Fiyi'); 
INSERT INTO country (country_id,country_name) VALUES (78,'Francia'); 
INSERT INTO country (country_id,country_name) VALUES (79,'Gabon'); 
INSERT INTO country (country_id,country_name) VALUES (80,'Gambia'); 
INSERT INTO country (country_id,country_name) VALUES (81,'Gaza Strip'); 
INSERT INTO country (country_id,country_name) VALUES (82,'Georgia'); 
INSERT INTO country (country_id,country_name) VALUES (83,'Ghana'); 
INSERT INTO country (country_id,country_name) VALUES (84,'Gibraltar'); 
INSERT INTO country (country_id,country_name) VALUES (85,'Granada'); 
INSERT INTO country (country_id,country_name) VALUES (86,'Grecia'); 
INSERT INTO country (country_id,country_name) VALUES (87,'Groenlandia'); 
INSERT INTO country (country_id,country_name) VALUES (88,'Guam'); 
INSERT INTO country (country_id,country_name) VALUES (89,'Guatemala'); 
INSERT INTO country (country_id,country_name) VALUES (90,'Guernsey'); 
INSERT INTO country (country_id,country_name) VALUES (91,'Guinea'); 
INSERT INTO country (country_id,country_name) VALUES (92,'Guinea Ecuatorial'); 
INSERT INTO country (country_id,country_name) VALUES (93,'Guinea-Bissau'); 
INSERT INTO country (country_id,country_name) VALUES (94,'Guyana'); 
INSERT INTO country (country_id,country_name) VALUES (95,'Haiti'); 
INSERT INTO country (country_id,country_name) VALUES (96,'Honduras'); 
INSERT INTO country (country_id,country_name) VALUES (97,'Hong Kong'); 
INSERT INTO country (country_id,country_name) VALUES (98,'Hungria'); 
INSERT INTO country (country_id,country_name) VALUES (99,'India'); 
INSERT INTO country (country_id,country_name) VALUES (100,'Indian Ocean'); 
INSERT INTO country (country_id,country_name) VALUES (101,'Indonesia'); 
INSERT INTO country (country_id,country_name) VALUES (102,'Iran'); 
INSERT INTO country (country_id,country_name) VALUES (103,'Iraq'); 
INSERT INTO country (country_id,country_name) VALUES (104,'Irlanda'); 
INSERT INTO country (country_id,country_name) VALUES (105,'Isla Bouvet'); 
INSERT INTO country (country_id,country_name) VALUES (106,'Isla Christmas'); 
INSERT INTO country (country_id,country_name) VALUES (107,'Isla Norfolk'); 
INSERT INTO country (country_id,country_name) VALUES (108,'Islandia'); 
INSERT INTO country (country_id,country_name) VALUES (109,'Islas Caiman'); 
INSERT INTO country (country_id,country_name) VALUES (110,'Islas Cocos'); 
INSERT INTO country (country_id,country_name) VALUES (111,'Islas Cook'); 
INSERT INTO country (country_id,country_name) VALUES (112,'Islas Feroe'); 
INSERT INTO country (country_id,country_name) VALUES (113,'Islas Georgia del Sur y Sandwich del Sur'); 
INSERT INTO country (country_id,country_name) VALUES (114,'Islas Heard y McDonald'); 
INSERT INTO country (country_id,country_name) VALUES (115,'Islas Malvinas'); 
INSERT INTO country (country_id,country_name) VALUES (116,'Islas Marianas del Norte'); 
INSERT INTO country (country_id,country_name) VALUES (117,'IslasMarshall'); 
INSERT INTO country (country_id,country_name) VALUES (118,'Islas Pitcairn'); 
INSERT INTO country (country_id,country_name) VALUES (119,'Islas Salomon'); 
INSERT INTO country (country_id,country_name) VALUES (120,'Islas Turcas y Caicos'); 
INSERT INTO country (country_id,country_name) VALUES (121,'Islas Virgenes Americanas'); 
INSERT INTO country (country_id,country_name) VALUES (122,'Islas Virgenes Britanicas'); 
INSERT INTO country (country_id,country_name) VALUES (123,'Israel'); 
INSERT INTO country (country_id,country_name) VALUES (124,'Italia'); 
INSERT INTO country (country_id,country_name) VALUES (125,'Jamaica'); 
INSERT INTO country (country_id,country_name) VALUES (126,'Jan Mayen'); 
INSERT INTO country (country_id,country_name) VALUES (127,'Japon'); 
INSERT INTO country (country_id,country_name) VALUES (128,'Jersey'); 
INSERT INTO country (country_id,country_name) VALUES (129,'Jordania'); 
INSERT INTO country (country_id,country_name) VALUES (130,'Kazajistan'); 
INSERT INTO country (country_id,country_name) VALUES (131,'Kenia'); 
INSERT INTO country (country_id,country_name) VALUES (132,'Kirguizistan'); 
INSERT INTO country (country_id,country_name) VALUES (133,'Kiribati'); 
INSERT INTO country (country_id,country_name) VALUES (134,'Kuwait'); 
INSERT INTO country (country_id,country_name) VALUES (135,'Laos'); 
INSERT INTO country (country_id,country_name) VALUES (136,'Lesoto'); 
INSERT INTO country (country_id,country_name) VALUES (137,'Letonia'); 
INSERT INTO country (country_id,country_name) VALUES (138,'Libano'); 
INSERT INTO country (country_id,country_name) VALUES (139,'Liberia'); 
INSERT INTO country (country_id,country_name) VALUES (140,'Libia'); 
INSERT INTO country (country_id,country_name) VALUES (141,'Liechtenstein'); 
INSERT INTO country (country_id,country_name) VALUES (142,'Lituania'); 
INSERT INTO country (country_id,country_name) VALUES (143,'Luxemburgo'); 
INSERT INTO country (country_id,country_name) VALUES (144,'Macao'); 
INSERT INTO country (country_id,country_name) VALUES (145,'Macedonia'); 
INSERT INTO country (country_id,country_name) VALUES (146,'Madagascar'); 
INSERT INTO country (country_id,country_name) VALUES (147,'Malasia'); 
INSERT INTO country (country_id,country_name) VALUES (148,'Malaui'); 
INSERT INTO country (country_id,country_name) VALUES (149,'Maldivas'); 
INSERT INTO country (country_id,country_name) VALUES (150,'Mali'); 
INSERT INTO country (country_id,country_name) VALUES (151,'Malta'); 
INSERT INTO country (country_id,country_name) VALUES (152,'Man, Isle of'); 
INSERT INTO country (country_id,country_name) VALUES (153,'Marruecos'); 
INSERT INTO country (country_id,country_name) VALUES (154,'Mauricio'); 
INSERT INTO country (country_id,country_name) VALUES (155,'Mauritania'); 
INSERT INTO country (country_id,country_name) VALUES (156,'Mayotte'); 
INSERT INTO country (country_id,country_name) VALUES (157,'Mexico'); 
INSERT INTO country (country_id,country_name) VALUES (158,'Micronesia'); 
INSERT INTO country (country_id,country_name) VALUES (159,'Moldavia'); 
INSERT INTO country (country_id,country_name) VALUES (160,'Monaco'); 
INSERT INTO country (country_id,country_name) VALUES (161,'Mongolia'); 
INSERT INTO country (country_id,country_name) VALUES (162,'Montserrat'); 
INSERT INTO country (country_id,country_name) VALUES (163,'Mozambique'); 
INSERT INTO country (country_id,country_name) VALUES (164,'Namibia'); 
INSERT INTO country (country_id,country_name) VALUES (165,'Nauru'); 
INSERT INTO country (country_id,country_name) VALUES (166,'Navassa Island'); 
INSERT INTO country (country_id,country_name) VALUES (167,'Nepal'); 
INSERT INTO country (country_id,country_name) VALUES (168,'Nicaragua'); 
INSERT INTO country (country_id,country_name) VALUES (169,'Niger'); 
INSERT INTO country (country_id,country_name) VALUES (170,'Nigeria'); 
INSERT INTO country (country_id,country_name) VALUES (171,'Niue'); 
INSERT INTO country (country_id,country_name) VALUES (172,'Noruega'); 
INSERT INTO country (country_id,country_name) VALUES (173,'Nueva Caledonia'); 
INSERT INTO country (country_id,country_name) VALUES (174,'Nueva Zelanda'); 
INSERT INTO country (country_id,country_name) VALUES (175,'Oman'); 
INSERT INTO country (country_id,country_name) VALUES (176,'Pacific Ocean'); 
INSERT INTO country (country_id,country_name) VALUES (177,'Paises Bajos'); 
INSERT INTO country (country_id,country_name) VALUES (178,'Pakistan'); 
INSERT INTO country (country_id,country_name) VALUES (179,'Palaos'); 
INSERT INTO country (country_id,country_name) VALUES (180,'Panama'); 
INSERT INTO country (country_id,country_name) VALUES (181,'Papua-Nueva Guinea'); 
INSERT INTO country (country_id,country_name) VALUES (182,'Paracel Islands'); 
INSERT INTO country (country_id,country_name) VALUES (183,'Paraguay'); 
INSERT INTO country (country_id,country_name) VALUES (184,'Peru'); 
INSERT INTO country (country_id,country_name) VALUES (185,'Polinesia Francesa'); 
INSERT INTO country (country_id,country_name) VALUES (186,'Polonia'); 
INSERT INTO country (country_id,country_name) VALUES (187,'Portugal'); 
INSERT INTO country (country_id,country_name) VALUES (188,'Puerto Rico'); 
INSERT INTO country (country_id,country_name) VALUES (189,'Qatar'); 
INSERT INTO country (country_id,country_name) VALUES (190,'Reino Unido'); 
INSERT INTO country (country_id,country_name) VALUES (191,'Republica Centroafricana'); 
INSERT INTO country (country_id,country_name) VALUES (192,'Republica Checa'); 
INSERT INTO country (country_id,country_name) VALUES (193,'Republica Democratica del Congo'); 
INSERT INTO country (country_id,country_name) VALUES (194,'Republica Dominicana'); 
INSERT INTO country (country_id,country_name) VALUES (195,'Ruanda'); 
INSERT INTO country (country_id,country_name) VALUES (196,'Rumania'); 
INSERT INTO country (country_id,country_name) VALUES (197,'Rusia'); 
INSERT INTO country (country_id,country_name) VALUES (198,'Sahara Occidental'); 
INSERT INTO country (country_id,country_name) VALUES (199,'Samoa'); 
INSERT INTO country (country_id,country_name) VALUES (200,'Samoa Americana'); 
INSERT INTO country (country_id,country_name) VALUES (201,'San Cristobal y Nieves'); 
INSERT INTO country (country_id,country_name) VALUES (202,'San Marino'); 
INSERT INTO country (country_id,country_name) VALUES (203,'San Pedro y Miquelon'); 
INSERT INTO country (country_id,country_name) VALUES (204,'San Vicente y las Granadinas'); 
INSERT INTO country (country_id,country_name) VALUES (205,'Santa Helena'); 
INSERT INTO country (country_id,country_name) VALUES (206,'Santa Lucia'); 
INSERT INTO country (country_id,country_name) VALUES (207,'Santo Tome y Principe'); 
INSERT INTO country (country_id,country_name) VALUES (208,'Senegal'); 
INSERT INTO country (country_id,country_name) VALUES (209,'Seychelles'); 
INSERT INTO country (country_id,country_name) VALUES (210,'Sierra Leona'); 
INSERT INTO country (country_id,country_name) VALUES (211,'Singapur'); 
INSERT INTO country (country_id,country_name) VALUES (212,'Siria'); 
INSERT INTO country (country_id,country_name) VALUES (213,'Somalia'); 
INSERT INTO country (country_id,country_name) VALUES (214,'Southern Ocean'); 
INSERT INTO country (country_id,country_name) VALUES (215,'Spratly Islands'); 
INSERT INTO country (country_id,country_name) VALUES (216,'Sri Lanka'); 
INSERT INTO country (country_id,country_name) VALUES (217,'Suazilandia'); 
INSERT INTO country (country_id,country_name) VALUES (218,'Sudafrica'); 
INSERT INTO country (country_id,country_name) VALUES (219,'Sudan'); 
INSERT INTO country (country_id,country_name) VALUES (220,'Suecia'); 
INSERT INTO country (country_id,country_name) VALUES (221,'Suiza'); 
INSERT INTO country (country_id,country_name) VALUES (222,'Surinam'); 
INSERT INTO country (country_id,country_name) VALUES (223,'Svalbard y Jan Mayen'); 
INSERT INTO country (country_id,country_name) VALUES (224,'Tailandia'); 
INSERT INTO country (country_id,country_name) VALUES (225,'Taiwan'); 
INSERT INTO country (country_id,country_name) VALUES (226,'Tanzania'); 
INSERT INTO country (country_id,country_name) VALUES (227,'Tayikistan'); 
INSERT INTO country (country_id,country_name) VALUES (228,'TerritorioBritanicodel Oceano Indico'); 
INSERT INTO country (country_id,country_name) VALUES (229,'Territorios Australes Franceses'); 
INSERT INTO country (country_id,country_name) VALUES (230,'Timor Oriental'); 
INSERT INTO country (country_id,country_name) VALUES (231,'Togo'); 
INSERT INTO country (country_id,country_name) VALUES (232,'Tokelau'); 
INSERT INTO country (country_id,country_name) VALUES (233,'Tonga'); 
INSERT INTO country (country_id,country_name) VALUES (234,'Trinidad y Tobago'); 
INSERT INTO country (country_id,country_name) VALUES (235,'Tunez'); 
INSERT INTO country (country_id,country_name) VALUES (236,'Turkmenistan'); 
INSERT INTO country (country_id,country_name) VALUES (237,'Turquia'); 
INSERT INTO country (country_id,country_name) VALUES (238,'Tuvalu'); 
INSERT INTO country (country_id,country_name) VALUES (239,'Ucrania'); 
INSERT INTO country (country_id,country_name) VALUES (240,'Uganda'); 
INSERT INTO country (country_id,country_name) VALUES (241,'Union Europea'); 
INSERT INTO country (country_id,country_name) VALUES (242,'Uruguay'); 
INSERT INTO country (country_id,country_name) VALUES (243,'Uzbekistan'); 
INSERT INTO country (country_id,country_name) VALUES (244,'Vanuatu'); 
INSERT INTO country (country_id,country_name) VALUES (245,'Venezuela'); 
INSERT INTO country (country_id,country_name) VALUES (246,'Vietnam'); 
INSERT INTO country (country_id,country_name) VALUES (247,'Wake Island'); 
INSERT INTO country (country_id,country_name) VALUES (248,'Wallis y Futuna'); 
INSERT INTO country (country_id,country_name) VALUES (249,'West Bank'); 
INSERT INTO country (country_id,country_name) VALUES (250,'World'); 
INSERT INTO country (country_id,country_name) VALUES (251,'Yemen'); 
INSERT INTO country (country_id,country_name) VALUES (252,'Yibuti'); 
INSERT INTO country (country_id,country_name) VALUES (253,'Zambia'); 
INSERT INTO country (country_id,country_name) VALUES (254,'Zimbabue'); 